version: '2'
services:
    jhipsteronlinesampleapplication-app:
        image: jhipsteronlinesampleapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipsteronlinesampleapplication-mysql:3306/jhipsteronlinesampleapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsteronlinesampleapplication-mysql:
        extends:
            file: mysql.yml
            service: jhipsteronlinesampleapplication-mysql
